pipelines:
  - name: MyApprovalGatesPipeline
    steps:
      - name: approvalGatesStep
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
        execution:
          onComplete:
            - echo "executing step..."
